---
- hosts: all      # target host(s)
  become: true    # sudo elevated
  tasks:

  - name: install apache2 package              # Nom afficher lors de l'execution de la task
    ansible.builtin.package:                       # Utiliser le built-in package manager 
      name: 
      - "{{ apache_package }}"   
      - "{{ php_package }}"                      
      state: latest                            # Permet d'avoir la dernier version
      update_cache: yes      # Conditional

 